# ruff: noqa: E501 - generated by alembic autogenerate; formatting is not hand-managed
"""baseline schema

Revision ID: 2fa1ed115369
Revises: 
Create Date: 2026-08-21 18:18:47.949917

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2fa1ed115369'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('normalized_query', sa.String(length=200), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_normalized_query'), 'searches', ['normalized_query'], unique=False)
    op.create_index(op.f('ix_searches_status'), 'searches', ['status'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=True),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('rank_components', sa.JSON(), nullable=True),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('duplicate_group_id', sa.String(length=36), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_search_id'), 'results', ['search_id'], unique=False)
    op.create_index('ix_results_search_rank', 'results', ['search_id', 'rank_score'], unique=False)
    op.create_table('source_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('quota_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_events_search_id'), 'source_events', ['search_id'], unique=False)
    op.create_table('duplicate_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_result_id', sa.String(length=36), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_evidence', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_result_id'], ['results.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_groups_search_id'), 'duplicate_groups', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_duplicate_groups_search_id'), table_name='duplicate_groups')
    op.drop_table('duplicate_groups')
    op.drop_index(op.f('ix_source_events_search_id'), table_name='source_events')
    op.drop_table('source_events')
    op.drop_index('ix_results_search_rank', table_name='results')
    op.drop_index(op.f('ix_results_search_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_searches_status'), table_name='searches')
    op.drop_index(op.f('ix_searches_normalized_query'), table_name='searches')
    op.drop_table('searches')
    # ### end Alembic commands ###
